// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using IOSUICollectonView.Model;
using UIKit;

namespace IOSUICollectonView
{
	public partial class DoctorGulfAcceptanceViewCell : UICollectionViewCell
	{
        DoctorsacceptingMedGulfInsuranceModel _model;

        public DoctorGulfAcceptanceViewCell (IntPtr handle) : base (handle)
		{

		}

        internal void ConfigureCell(DoctorsacceptingMedGulfInsuranceModel model)
        {
            _model = model;

            try
            {

                _model = model;
                DrName.Text = model.name;
                ReviewrsCount.Text = model.reviewrCount.ToString();
                Specification.Text = model.specification;
                Degree.Text = model.department;
                DoctorImage.Image = UIImage.FromBundle(model.image);
               // RatingView.AddSubview(ratingView);

            }
            catch (Exception ex) { }
        }

    }
}
