// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Drawing;
using CoreAnimation;
using CoreGraphics;
using Foundation;
using IOSUICollectonView.Model;
using Rating;
using UIKit;

namespace IOSUICollectonView
{
	public partial class HappyCustomerViewCell : UICollectionViewCell
	{
       public static readonly NSString Key = new NSString("RatingsCell");
        PDRatingView ratingView;
        public void Update(decimal rating)
        {
            decimal halfRoundedRating = Math.Round(rating * 2m, MidpointRounding.AwayFromZero) / 2m;
           ratingView.AverageRating = rating;
        }

        public HappyCustomerViewCell (IntPtr handle) : base (handle)
		{
            VerticalStack = new UIStackView();
            this.Layer.BorderColor = UIColor.LightGray.CGColor;
            this.Layer.BorderWidth = 1.0f;
            this.Layer.CornerRadius = 10;
            //this.SizeToFit();
            this.BackgroundColor = UIColor.White;
            this.Transform = CGAffineTransform.MakeScale(0.8f, 0.8f);
         
            var ratingConfig = new RatingConfig(emptyImage: UIImage.FromBundle("empty"),
                                                filledImage: UIImage.FromBundle("filled"),
                                                chosenImage: UIImage.FromBundle("chosen"));
            ratingView = new PDRatingView(new CGRect(CGPoint.Empty, ContentView.Bounds.Size), ratingConfig);
            ratingView.UserInteractionEnabled = false;
 

        }
        HappyCustomersModel _model;
       // UIImageView imageView;
       [Export("awakeFromNib")]
        public override void AwakeFromNib()
        {
            try
            {
                base.AwakeFromNib();
           
                RatingView.AddSubview(ratingView);

            }
            catch (Exception ex) { }

        }
       public HappyCustomerViewCell(CGRect frame) : base(frame)
        {
            BackgroundView = new UIView { BackgroundColor = UIColor.Orange };

          //  SelectedBackgroundView = new UIView { BackgroundColor = UIColor.Green };

            ContentView.Layer.BorderColor = UIColor.LightGray.CGColor;
            ContentView.Layer.BorderWidth = 2.0f;
            ContentView.BackgroundColor = UIColor.White;
            ContentView.Transform = CGAffineTransform.MakeScale(0.8f, 0.8f);

            //imageView = new UIImageView(UIImage.FromBundle("placeholder.png"));
            //imageView.Center = ContentView.Center;
            //imageView.Transform = CGAffineTransform.MakeScale(0.7f, 0.7f);

            /*var ratingConfig = new RatingConfig(emptyImage: UIImage.FromBundle("Stars/empty"),
                                                filledImage: UIImage.FromBundle("Stars/filled"),
                                                chosenImage: UIImage.FromBundle("Stars/chosen"));
            ratingView = new PDRatingView(new CGRect(CGPoint.Empty, ContentView.Bounds.Size), ratingConfig);
            ratingView.UserInteractionEnabled = false;
            ratingConfig.ItemPadding = 5f;
            ratingConfig.ScaleSize = 5;
            RatingView.Add(ratingView);*/

        }
        internal void ConfigureCell(HappyCustomersModel model)
        {
            try
            {

                _model = model;
                NameLabel.Text = model.name;
                AgeLbl.Text = model.age.ToString();
                DrNameLbl.Text = model.drName;
                ReviewCountLbl.Text = model.reviewrCount.ToString() ;
                DayCountLabll.Text = model.sinceDays.ToString();
                DeptNameLbl.Text = model.department;
                DescriptionLabel.Text = model.review;
               UserImage.Image=  UIImage.FromBundle(model.image);
                DRImage.Image= UIImage.FromBundle(model.doctorImage);
                reviewImage.Image = UIImage.FromBundle(model.reviewImage);
                RatingView.AddSubview(ratingView);
             
            }
            catch (Exception ex) { }
        }

    }
}
